spring.application.name=fadex-backend

# conexion BD
spring.datasource.url=jdbc:postgresql://localhost:5432/FedexBarberia
spring.datasource.username=postgres
spring.datasource.password=admin

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# FlyWay
spring.flyway.enabled=true
spring.flyway.locations=classpath:db.migration

# SECURITY
spring.security.user.name=admin
spring.security.user.password=1234