
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.lqzgedqjntomzubacvqi
spring.datasource.password=TF8D111CD207C


spring.datasource.driver-class-name=org.postgresql.Driver

# FlyWay
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# SECURITY
spring.security.user.name=admin
spring.security.user.password=1234
# token
jwt.secret=b92b92ced5e768054fd5d7c19727efd701d1ea3db94a34eae1dd5f38c869bdf4
jwt.expiration=900000
jwt.refresh-expiration-days=7

file.upload-dir=uploads/

server.port=8081