spring.application.name=fadex-backend

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.lqzgedqjntomzubacvqi
spring.datasource.password=TF8D111CD207C


spring.datasource.driver-class-name=org.postgresql.Driver

# FlyWay
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# SECURITY
spring.security.user.name=admin
spring.security.user.password=1234